//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zinderud.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zinderud.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///              xmlns:xrd=&quot;clr-namespace:CodeReason.Reports.Document;assembly=CodeReason.Reports&quot; 
        ///              xmlns:i=&quot;http://schemas.microsoft.com/expression/2010/interactivity&quot;
        ///              xmlns:triggers=&quot;clr-namespace:MVVM;assembly=MVVM&quot;
        ///              xmlns:ei=&quot;http://schemas.microsoft.com/expression/2010/interactions&quot; 
        ///              DataContext=&quot;{B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ArsivSetRaporu {
            get {
                return ResourceManager.GetString("ArsivSetRaporu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///              xmlns:xrd=&quot;clr-namespace:CodeReason.Reports.Document;assembly=CodeReason.Reports&quot; 
        ///              xmlns:i=&quot;http://schemas.microsoft.com/expression/2010/interactivity&quot;
        ///              xmlns:triggers=&quot;clr-namespace:MVVM;assembly=MVVM&quot;
        ///              xmlns:ei=&quot;http://schemas.microsoft.com/expression/2010/interactions&quot; 
        ///              DataContext=&quot;{B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KBTestRapor {
            get {
                return ResourceManager.GetString("KBTestRapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.0&quot; /&gt;
        ///  &lt;/startup&gt;
        ///  
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;log4net&quot; type=&quot;log4net.Config.Log4NetConfigurationSectionHandler,Log4net&quot;/&gt;
        ///  &lt;/configSections&gt;
        ///  
        ///  &lt;log4net&gt;
        ///    &lt;logger name=&quot;Görüntü.ViewModel.KirliAlanViewModel&quot;&gt;
        ///      &lt;appender-ref ref=&quot;UdpAppender&quot; /&gt;
        ///    &lt;/logger&gt;
        ///    &lt;logger name=&quot;Görüntü.ViewModel.AdminViewModel&quot;&gt;
        ///      &lt;appender-ref ref [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log4net {
            get {
                return ResourceManager.GetString("log4net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///              xmlns:xrd=&quot;clr-namespace:CodeReason.Reports.Document;assembly=CodeReason.Reports&quot; 
        ///              xmlns:i=&quot;http://schemas.microsoft.com/expression/2010/interactivity&quot;
        ///              xmlns:triggers=&quot;clr-namespace:MVVM;assembly=MVVM&quot;
        ///              xmlns:ei=&quot;http://schemas.microsoft.com/expression/2010/interactions&quot; 
        ///              DataContext=&quot;{B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtoklavTestRapor {
            get {
                return ResourceManager.GetString("OtoklavTestRapor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FlowDocument  xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///              xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///              xmlns:xrd=&quot;clr-namespace:CodeReason.Reports.Document;assembly=CodeReason.Reports&quot; 
        ///                 xmlns:i=&quot;http://schemas.microsoft.com/expression/2010/interactivity&quot;
        ///                  xmlns:triggers=&quot;clr-namespace:MVVM;assembly=MVVM&quot;
        ///        xmlns:ei=&quot;http://schemas.microsoft.com/expression/2010/interactions&quot; 
        ///          xmlns:s=&quot;clr-name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleReport {
            get {
                return ResourceManager.GetString("SimpleReport", resourceCulture);
            }
        }
    }
}
