/*
murat onur karadeniz
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/12/19 - 17:30:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using AutoBusinessObjects;
using DataObjects.EntityFramework;
using System.Data.Objects.DataClasses;

namespace DataObjects.ModelMapper
{

    /// <summary>
    /// Assembler for <see cref="TBL_URUN"/> and <see cref="TBL_URUNDTO"/>.
    /// </summary>
    //public static partial class TBL_URUNMaping
    //{
    //    /// <summary>
    //    /// Invoked when <see cref="ToDTO"/> operation is about to return.
    //    /// </summary>
    //    /// <param name="dto"><see cref="TBL_URUNDTO"/> converted from <see cref="TBL_URUN"/>.</param>
    //    static partial void OnDTO(this TBL_URUN entity, TBL_URUNDTO dto);

    //    /// <summary>
    //    /// Invoked when <see cref="ToEntity"/> operation is about to return.
    //    /// </summary>
    //    /// <param name="entity"><see cref="TBL_URUN"/> converted from <see cref="TBL_URUNDTO"/>.</param>
    //    static partial void OnEntity(this TBL_URUNDTO dto, TBL_URUN entity);

    //    /// <summary>
    //    /// Converts this instance of <see cref="TBL_URUNDTO"/> to an instance of <see cref="TBL_URUN"/>.
    //    /// </summary>
    //    /// <param name="dto"><see cref="TBL_URUNDTO"/> to convert.</param>
    //    public static TBL_URUN ToEntity(this TBL_URUNDTO dto)
    //    {
    //        if (dto == null) return null;

    //        var entity = new TBL_URUN();

    //        entity.ID = dto.ID;
    //        entity.URUN_ADI = dto.URUN_ADI;
    //        entity.URUN_TIPI = dto.URUN_TIPI;
    //        entity.URUN_GELIS_FIYATI = dto.URUN_GELIS_FIYATI;
    //        entity.URUN_SATIS_FIYATI = dto.URUN_SATIS_FIYATI;
    //        entity.URUN_STOK_MÝKTARI = dto.URUN_STOK_MÝKTARI;

    //        dto.OnEntity(entity);

    //        return entity;
    //    }

    //    /// <summary>
    //    /// Converts this instance of <see cref="TBL_URUN"/> to an instance of <see cref="TBL_URUNDTO"/>.
    //    /// </summary>
    //    /// <param name="entity"><see cref="TBL_URUN"/> to convert.</param>
    //    public static TBL_URUNDTO ToDTO(this TBL_URUN entity)
    //    {
    //        if (entity == null) return null;

    //        var dto = new TBL_URUNDTO();

    //        dto.ID = entity.ID;
    //        dto.URUN_ADI = entity.URUN_ADI;
    //        dto.URUN_TIPI = entity.URUN_TIPI;
    //        dto.URUN_GELIS_FIYATI = entity.URUN_GELIS_FIYATI;
    //        dto.URUN_SATIS_FIYATI = entity.URUN_SATIS_FIYATI;
    //        dto.URUN_STOK_MÝKTARI = entity.URUN_STOK_MÝKTARI;

    //        entity.OnDTO(dto);

    //        return dto;
    //    }

    //    /// <summary>
    //    /// Converts each instance of <see cref="TBL_URUNDTO"/> to an instance of <see cref="TBL_URUN"/>.
    //    /// </summary>
    //    /// <param name="dtos"></param>
    //    /// <returns></returns>
    //    public static List<TBL_URUN> ToEntities(this IEnumerable<TBL_URUNDTO> dtos)
    //    {
    //        if (dtos == null) return null;

    //        return dtos.Select(e => e.ToEntity()).ToList();
    //    }

    //    /// <summary>
    //    /// Converts each instance of <see cref="TBL_URUN"/> to an instance of <see cref="TBL_URUNDTO"/>.
    //    /// </summary>
    //    /// <param name="entities"></param>
    //    /// <returns></returns>
    //    public static List<TBL_URUNDTO> ToDTOs(this IEnumerable<TBL_URUN> entities)
    //    {
    //        if (entities == null) return null;

    //        return entities.Select(e => e.ToDTO()).ToList();
    //    }

    //}

    ///// <summary>
    ///// Assembler for <see cref="TBL_ODEME_TIPI"/> and <see cref="TBL_ODEME_TIPIDTO"/>.
    ///// </summary>
    //public static partial class TBL_ODEME_TIPIMaping
    //{
    //    /// <summary>
    //    /// Invoked when <see cref="ToDTO"/> operation is about to return.
    //    /// </summary>
    //    /// <param name="dto"><see cref="TBL_ODEME_TIPIDTO"/> converted from <see cref="TBL_ODEME_TIPI"/>.</param>
    //    static partial void OnDTO(this TBL_ODEME_TIPI entity, TBL_ODEME_TIPIDTO dto);

    //    /// <summary>
    //    /// Invoked when <see cref="ToEntity"/> operation is about to return.
    //    /// </summary>
    //    /// <param name="entity"><see cref="TBL_ODEME_TIPI"/> converted from <see cref="TBL_ODEME_TIPIDTO"/>.</param>
    //    static partial void OnEntity(this TBL_ODEME_TIPIDTO dto, TBL_ODEME_TIPI entity);

    //    /// <summary>
    //    /// Converts this instance of <see cref="TBL_ODEME_TIPIDTO"/> to an instance of <see cref="TBL_ODEME_TIPI"/>.
    //    /// </summary>
    //    /// <param name="dto"><see cref="TBL_ODEME_TIPIDTO"/> to convert.</param>
    //    public static TBL_ODEME_TIPI ToEntity(this TBL_ODEME_TIPIDTO dto)
    //    {
    //        if (dto == null) return null;

    //        var entity = new TBL_ODEME_TIPI();

    //        entity.ID = dto.ID;
    //        entity.ODEME_TIPI = dto.ODEME_TIPI;

    //        dto.OnEntity(entity);

    //        return entity;
    //    }

    //    /// <summary>
    //    /// Converts this instance of <see cref="TBL_ODEME_TIPI"/> to an instance of <see cref="TBL_ODEME_TIPIDTO"/>.
    //    /// </summary>
    //    /// <param name="entity"><see cref="TBL_ODEME_TIPI"/> to convert.</param>
    //    public static TBL_ODEME_TIPIDTO ToDTO(this TBL_ODEME_TIPI entity)
    //    {
    //        if (entity == null) return null;

    //        var dto = new TBL_ODEME_TIPIDTO();

    //        dto.ID = entity.ID;
    //        dto.ODEME_TIPI = entity.ODEME_TIPI;

    //        entity.OnDTO(dto);

    //        return dto;
    //    }

    //    /// <summary>
    //    /// Converts each instance of <see cref="TBL_ODEME_TIPIDTO"/> to an instance of <see cref="TBL_ODEME_TIPI"/>.
    //    /// </summary>
    //    /// <param name="dtos"></param>
    //    /// <returns></returns>
    //    public static List<TBL_ODEME_TIPI> ToEntities(this IEnumerable<TBL_ODEME_TIPIDTO> dtos)
    //    {
    //        if (dtos == null) return null;

    //        return dtos.Select(e => e.ToEntity()).ToList();
    //    }

    //    /// <summary>
    //    /// Converts each instance of <see cref="TBL_ODEME_TIPI"/> to an instance of <see cref="TBL_ODEME_TIPIDTO"/>.
    //    /// </summary>
    //    /// <param name="entities"></param>
    //    /// <returns></returns>
    //    public static List<TBL_ODEME_TIPIDTO> ToDTOs(this IEnumerable<TBL_ODEME_TIPI> entities)
    //    {
    //        if (entities == null) return null;

    //        return entities.Select(e => e.ToDTO()).ToList();
    //    }

    //}
}
